### ISSUE TITLE
Review: Overview

### ISSUE THREAD

**Issue by radeonxray** [edipetres/UFO-blog-post#1]
**Zaeem:**

- Nice to see that the blog is separated by subheadings and a good mix of images and text. 
- Looks like you have followed Kent Beck abstracts, which is good. However, it would have looked better if you in some way had made clear where your abstract started (and ended).

**Christian:**
- Ok intro to the topic
- Fine implementation of the abstract.
- It feels like the Abstract was expanded a lot, and the end result was used for/as the intro.
- What is talked about in the intro matches the Title of the blog great.
- I really miss just a couple of lines explaining “what and how we are going to show it in this blog”, because the team seems to have nailed the “What is this topic about” and a bit of the “what we are going to show”.

If it wasn't for the “blue additions” to the review criteria, we would have scored it a bit lower.

**Score: 6**

**Comment by edipetres** [comment]
# Fix:
1. Style abstraction with italics
2. Explain better in the beginning how the evidence is going to solve the problem (“what and how we are going to show it in this blog”)

**Comment by Nexao** [comment]
Have updated abstraction and have gone more into making better explanations
