### ISSUE TITLE
Review: Reliable Data from Credible Sources

### ISSUE THREAD

**Issue by radeonxray** [edipetres/UFO-blog-post#2]
**Zaeem:**
- You have only used very few sources and have not referred to them anywhere throughout the blog. 
- In addition, many sources are simply referencing to images. 
- Furthermore, one of the sources refers to a blog that is subjective and just based on someone else's opinions.
- I do not like that you start your blog with this claim without substantiating it with anything at all: “_Developer teams spend too much time setting up and maintaining IT infrastructures_”. It's okay not to substantiate the claim in your abstract, but you should have done it somewhere in the blog, e.g. with some data from a reliable source.
- However, it is great to see that there are also used sources from Amazon’s official website.

**Christian:**

- Sources are listed in the bottom of the blog, totally super, no complaints there.
- Good reliable sources, though I can’t really vouch for the Oliver-blog, since I can’t find any solid info on him and his background.
- Sources lack time/date stamps for when visited! 
- The provided sources are not referenced anywhere in the blog itself! Not even as simple hyperlinks within the blog itself and nor the source-list.
- In “Managed Services”, you have a beautiful diagram depicting the life cycle of software development. I have Looked through the 5 sources you have provided, but I can’t find the source that backs up your numbers.
  - I did not go through all the potential sub-links with the provided source links, since I would expect at least one of the provided sources would show me the data to back up your claims. If I have to dig for the data myself, you failed me ):
- There are examples of pieces of text from your sources that either should have been quoted or at least referenced
  - Blog: _They’re guarded 24/7 by trained security guards on a facility that enforces least privilege basis._ 
  - Source: _Data centres are staffed 24×7 by trained security guards, and access is authorized strictly on a least privileged basis_
   -[Source](http://www.tothenew.com/blog/top-10-benefits-of-using-aws/)

**Score: 2** (_but you are seriously kissing the border to 1_)

**Comment by Nexao** [comment]
Fix:

Will make sure to add links to where they're used and will update the quotes.

**Comment by Nexao** [comment]
Have updated sources for parts where we get external information and made references for charts
