### ISSUE TITLE
Review: Design Constraints and Assumptions

### ISSUE THREAD

**Issue by radeonxray** [edipetres/UFO-blog-post#3]
**Zaeem:**
 - You make a series of comparisons, which is good. E.g. you compare GUI vs Command Line interface 
 - showed on an image and explains about the pros and cons of both. 
 - The benefit of using AWS is clearly highlighted throughout the blog.
- However, you should have gone into more depth with your subjects.

**Christian:**
 - Lacks explanation of constraints of their technology choices.
 - Areas with a little explanation:
 - Pay Per Us, a small insight into what to do if traffic is low vs. high
 - Technologies used:
  - AWS
  - Continuous Integration (CI) 
  - Elastic Beanstalk
 - No examples of their own work being used in the blog, has provided screenshots of generic projects from AWS.
 - Only a few alternatives technologies are mentioned, but never detailed or explored in depths.
   - Version Control System Github vs. Bitbucket
   - AWS Configuration: GUI vs. Command Line Interface
     - Has a few lines of pro’s and con’s

Because you dropped the ball regarding your sources and data, it hurts our review of this section. In general, while you did have a few vague constraints, we general felt you lacked a lot of alternative choices, discussion of those and justification for your choices.

**Score: 5**

**Comment by edipetres** [comment]
It is true that a reference is missing for a chart and it will be fixed. But otherwise, a lot of the points come from own experience working with AWS during the project - which is opinion.

# Fix
- explain what constraints come with AWS
- add alternatives to AWS (Microsoft Azure, Google's CSP)
- add references to presumptions made, or explain our chain of thought more logically

**Comment by radeonxray** [comment]
> ... But otherwise, a lot of the points come from own experience working with AWS during the project - which is opinion.

Totally fair point, we just would have loved to see those points in better context with the experience you've gained during the project (:

**Comment by Nexao** [comment]
Have added alternatives and made it more focused on both pros and cons, instead of just looking like an "ad"
