### ISSUE TITLE
Review: Theoretical Explanations

### ISSUE THREAD

**Issue by Zaeem96** [edipetres/UFO-blog-post#5]
**Zaeem:**

- There are not many theoretical explanations, which means that this one is difficult to evaluate…
- Some words/tools are not explained, e.g. “_Elastic Beanstalk_” - you just assume that the reader knows about them.

**Christian:**

- Other than the Abstract, not much theory shown or proven in the blog.
- Blog seems to have been written more as a “practical”-blog, rather than a theoretical-blog (which is fine), but the topics don’t include the teams own project for context to support their abstract. 

Lack of theory for the topics, not much support for the practical approach either. It feels more like an opinion-piece, that lacks the teeth and arguments to back it up.  

**Score: 5**

**Comment by Nexao** [comment]
Fix:

Will update technical terms for AWS words

Will include more about project

**Comment by Nexao** [comment]
Updated technical terms and included more about project
