### ISSUE TITLE
Review: Design Criteria, Sample Calculations and Simulations

### ISSUE THREAD

**Issue by Zaeem96** [edipetres/UFO-blog-post#6]
**Zaeem:**

- I could not find any simulations, so this one is also difficult to rate.
- Repeat yourself is never good: “…_you’re able to keep an eye on everything that’s going on_…” and right after: “_You’re able to keep track of exactly what’s going on_”.
- Nice explanation (including image) of the part about “Scalability”.
- But where does your pie chart come from? I can’t find it anywhere in your sources. Is that something you have assumed? What is your evidence?

**Christian:**

- Only one calculation
- The low vs. high cost in the “Pay Per Use”-section
- Good explanation about the Scalability and the picture.
- Where is that Managed Service diagram and data from?
- Lacks simulations (Could be ignored, if enough solid calculations)
- Lack of Design Criteria, examples and explanations from a project

**Score: 5**

**Comment by Nexao** [comment]
Have added more calculations and made references to the sources of the information
