### ISSUE TITLE
Review: Previous Work/Future Work

### ISSUE THREAD

**Issue by Zaeem96** [edipetres/UFO-blog-post#7]
**Zaeem:**

- You only mention your own experience with AWS very briefly and you do not mention anything about the future…

**Christian:**

- You should have included your LSD or SI-project to provide better context and examples for the topics.
- “_Outlook discussion Having hosted our website on AWS has been a great experience. It allowed us to spend our time on creating the website and the corresponding subsystems for it, while we also learned about aspects of website hosting from the best in the field like scaling, security and managed services in general._”
    - Only provides a very vague and small glimpse into your project 
- No talk about future project, what to look out for or wanted to change the next time.

**Score: 2**

**Comment by edipetres** [comment]
# Fix
- describe the experience with AWS with regard to the hackernews project
- include outlook for the future regarding the use of Cloud Service Providers

**Comment by Nexao** [comment]
We have now included our hackernews project and we are talking about future too
